wp:
  name: wpapp
  labels:
    app: wp
    env: dev
    stack: wordpress
    id: c0924651
    
  image:
    repository: wordpress
    tag: latest
    pullPolicy: Always
  replicas: 1
  configmap:
    ## KEY: "value"
    APP_ENV: dev
    WORDPRESS_DB_HOST: wp-database.wpdb1.svc.cluster.local:3306
    WORDPRESS_DB_NAME: C0924651
    WORDPRESS_DB_USER: 3324_user
  containerPorts:
      http: 80
